#!/bin/bash

export osmandmapcreatorpath="/opt/OsmAndMapCreator"

export osmmemory=${osmmemory:-"-Xms256M -Xmx1024M"}

#osmproxy=${osmproxy:-"-DsocksProxyHost=vl10387.pre.cz -DsocksProxyPort=3306"}
export osmproxy=${osmproxy:-""}
export osmtimeout=${osmtimeout:-"-Dsun.net.client.defaultConnectTimeout=2500 -Dsun.net.client.defaultReadTimeout=2500"}
export osmlibrary=${osmlibrary:-"-cp $osmandmapcreatorpath/OsmAndMapCreator.jar:$osmandmapcreatorpath/lib/OsmAnd-core.jar:$osmandmapcreatorpath/lib/*.jar:$osmandmapcreatorpath/lib-gl/*.jar"}

echo "variables loaded"
