#!/bin/bash
test -e "./variables" && ./variables

osmmemory=${osmmemory:-"-Xms256M -Xmx1024M"}
osmproxy=${osmproxy:-"-DsocksProxyHost=vl10387.pre.cz -DsocksProxyPort=3306"}
osmtimeout=${osmtimeout:-"-Dsun.net.client.defaultConnectTimeout=2500 -Dsun.net.client.defaultReadTimeout=2500"}
osmlibrary=${osmlibrary:-"-cp \"./OsmAndMapCreator.jar:./lib/OsmAnd-core.jar:./lib/*.jar:./lib-gl/*.jar\""}

java ${memory} ${proxy} ${timeout} ${library} net.osmand.swing.OsmExtractionUI
