#!/bin/bash
test -e "./variables" && source ./variables

osmmemory=${osmmemory:-"-Xms512M -Xmx2048M"}
osmproxy=${osmproxy:-""}
osmtimeout=${osmtimeout:-"-Dsun.net.client.defaultConnectTimeout=2500 -Dsun.net.client.defaultReadTimeout=2500"}
osmlibrary=${osmlibrary:-"-cp ./OsmAndMapCreator.jar:./lib/OsmAnd-core.jar:./lib/*.jar:./lib-gl/*.jar"}

cmd="java ${osmmemory} ${osmproxy} ${osmtimeout} ${osmlibrary} net.osmand.swing.OsmExtractionUI"
echo $cmd
$cmd
